#!/bin/bash
# Lab Export Script
# Packages labs for distribution
# Usage: ./export-lab.sh <lab-name> [options]

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(dirname "$SCRIPT_DIR")"
LABS_DIR="$ROOT_DIR/labs"
EXPORT_DIR="$ROOT_DIR/exports"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

show_help() {
    echo "Lab Export Tool - Security Lab Factory"
    echo ""
    echo "Usage: $0 <lab-name> [options]"
    echo ""
    echo "Formats:"
    echo "  --format docker      Docker bundle (.lab.tar.gz)"
    echo "  --format terraform   Terraform module"
    echo "  --format kubernetes  Kubernetes manifests"
    echo "  --format helm        Helm chart"
    echo ""
    echo "Options:"
    echo "  --author NAME        Set author name"
    echo "  --license TYPE       License type (MIT, Apache, Commercial)"
    echo "  --price AMOUNT       Price in USD (0 = free)"
    echo "  --include-solutions  Include flag solutions"
    echo "  --output DIR         Output directory"
    echo "  --help               Show this help"
    echo ""
    echo "Examples:"
    echo "  $0 sqli-lab --format docker"
    echo "  $0 ctf-lab --format docker --license Commercial --price 29"
}

# Default values
LAB_NAME=""
FORMAT="docker"
AUTHOR=""
LICENSE="MIT"
PRICE=0
INCLUDE_SOLUTIONS=false
OUTPUT_DIR="$EXPORT_DIR"

# Parse arguments
while [[ $# -gt 0 ]]; do
    case $1 in
        --format)
            FORMAT="$2"
            shift 2
            ;;
        --author)
            AUTHOR="$2"
            shift 2
            ;;
        --license)
            LICENSE="$2"
            shift 2
            ;;
        --price)
            PRICE="$2"
            shift 2
            ;;
        --include-solutions)
            INCLUDE_SOLUTIONS=true
            shift
            ;;
        --output)
            OUTPUT_DIR="$2"
            shift 2
            ;;
        --help|-h)
            show_help
            exit 0
            ;;
        -*)
            echo -e "${RED}Unknown option: $1${NC}"
            exit 1
            ;;
        *)
            LAB_NAME="$1"
            shift
            ;;
    esac
done

# Validate
if [ -z "$LAB_NAME" ]; then
    echo -e "${RED}Error: Lab name required${NC}"
    show_help
    exit 1
fi

LAB_PATH="$LABS_DIR/$LAB_NAME"
if [ ! -d "$LAB_PATH" ]; then
    echo -e "${RED}Error: Lab '$LAB_NAME' not found at $LAB_PATH${NC}"
    exit 1
fi

mkdir -p "$OUTPUT_DIR"

echo -e "${BLUE}Exporting lab: $LAB_NAME${NC}"
echo "Format: $FORMAT"
echo "License: $LICENSE"
echo "Price: \$$PRICE"
echo ""

# Create manifest
MANIFEST_FILE=$(mktemp)
cat > "$MANIFEST_FILE" << EOF
# Lab Manifest
name: "$LAB_NAME"
version: "1.0.0"
author: "${AUTHOR:-Security Lab Factory}"
license: "$LICENSE"
price: $PRICE
export_date: "$(date -Iseconds)"
format: "$FORMAT"
generator: "security-lab-factory"

checksums:
EOF

case $FORMAT in
    docker)
        EXPORT_FILE="$OUTPUT_DIR/${LAB_NAME}.lab.tar.gz"
        echo "Creating Docker bundle..."

        # Create temp directory
        TEMP_DIR=$(mktemp -d)
        cp -r "$LAB_PATH"/* "$TEMP_DIR/"

        # Remove solutions if not included
        if [ "$INCLUDE_SOLUTIONS" = false ]; then
            rm -rf "$TEMP_DIR/flags/solutions"/*.txt 2>/dev/null || true
        fi

        # Add manifest
        cp "$MANIFEST_FILE" "$TEMP_DIR/lab-manifest.yaml"

        # Create tarball
        tar -czf "$EXPORT_FILE" -C "$TEMP_DIR" .

        # Calculate checksum
        CHECKSUM=$(sha256sum "$EXPORT_FILE" | cut -d' ' -f1)
        echo "  - file: $(basename $EXPORT_FILE)" >> "$MANIFEST_FILE"
        echo "    sha256: $CHECKSUM" >> "$MANIFEST_FILE"

        rm -rf "$TEMP_DIR"

        echo -e "${GREEN}Exported: $EXPORT_FILE${NC}"
        echo "SHA256: $CHECKSUM"
        ;;

    terraform)
        EXPORT_DIR_TF="$OUTPUT_DIR/${LAB_NAME}-terraform"
        echo "Creating Terraform module..."

        mkdir -p "$EXPORT_DIR_TF"

        # Convert docker-compose to terraform
        cat > "$EXPORT_DIR_TF/main.tf" << 'TFEOF'
# Terraform module for Security Lab
# Generated by Security Lab Factory

terraform {
  required_providers {
    docker = {
      source  = "kreuzwerker/docker"
      version = "~> 3.0"
    }
  }
}

variable "lab_name" {
  description = "Name of the lab"
  type        = string
}

variable "network_name" {
  description = "Docker network name"
  type        = string
  default     = "lab-network"
}

resource "docker_network" "lab_network" {
  name = var.network_name
}

# Add service resources based on docker-compose.yml
TFEOF

        cp "$LAB_PATH/docker-compose.yml" "$EXPORT_DIR_TF/"
        cp "$MANIFEST_FILE" "$EXPORT_DIR_TF/lab-manifest.yaml"

        echo -e "${GREEN}Exported: $EXPORT_DIR_TF${NC}"
        ;;

    kubernetes)
        EXPORT_DIR_K8S="$OUTPUT_DIR/${LAB_NAME}-k8s"
        echo "Creating Kubernetes manifests..."

        mkdir -p "$EXPORT_DIR_K8S"

        # Create namespace
        cat > "$EXPORT_DIR_K8S/namespace.yaml" << EOF
apiVersion: v1
kind: Namespace
metadata:
  name: $LAB_NAME
  labels:
    app: security-lab
EOF

        # Note: Full conversion would use kompose
        echo "Note: Use 'kompose convert' for full docker-compose conversion"

        cp "$LAB_PATH/docker-compose.yml" "$EXPORT_DIR_K8S/"
        cp "$MANIFEST_FILE" "$EXPORT_DIR_K8S/lab-manifest.yaml"

        echo -e "${GREEN}Exported: $EXPORT_DIR_K8S${NC}"
        ;;

    helm)
        EXPORT_DIR_HELM="$OUTPUT_DIR/${LAB_NAME}-helm"
        echo "Creating Helm chart..."

        mkdir -p "$EXPORT_DIR_HELM/templates"

        # Chart.yaml
        cat > "$EXPORT_DIR_HELM/Chart.yaml" << EOF
apiVersion: v2
name: $LAB_NAME
description: Security Lab - $LAB_NAME
version: 1.0.0
appVersion: "1.0"
EOF

        # values.yaml
        cat > "$EXPORT_DIR_HELM/values.yaml" << EOF
# Default values for $LAB_NAME
replicaCount: 1

image:
  repository: security-lab/$LAB_NAME
  pullPolicy: IfNotPresent
  tag: "latest"

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi
EOF

        cp "$MANIFEST_FILE" "$EXPORT_DIR_HELM/lab-manifest.yaml"

        echo -e "${GREEN}Exported: $EXPORT_DIR_HELM${NC}"
        ;;

    *)
        echo -e "${RED}Unknown format: $FORMAT${NC}"
        exit 1
        ;;
esac

rm -f "$MANIFEST_FILE"

echo ""
echo -e "${GREEN}Export complete!${NC}"
echo ""
echo "Next steps:"
if [ "$PRICE" -gt 0 ]; then
    echo "  - Upload to marketplace (Gumroad, etc.)"
    echo "  - Set up payment processing"
else
    echo "  - Share on GitHub"
    echo "  - Add to community catalog"
fi
