# AWS Cloud Security Lab (LocalStack)
# Usage: docker-compose -f aws-localstack.yaml up -d
# Simulates AWS services locally for security testing

version: '3.8'

networks:
  cloud-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.40.0.0/24

services:
  # LocalStack - AWS Services Emulator
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - "4566:4566"           # LocalStack Gateway
      - "4510-4559:4510-4559" # External services port range
    networks:
      cloud-net:
        ipv4_address: 172.40.0.10
    environment:
      - SERVICES=s3,iam,lambda,ec2,secretsmanager,ssm,sts,dynamodb,sqs,sns
      - DEBUG=1
      - DATA_DIR=/var/lib/localstack/data
      - DOCKER_HOST=unix:///var/run/docker.sock
      - AWS_DEFAULT_REGION=us-east-1
    volumes:
      - localstack-data:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock
      - ./aws-init:/docker-entrypoint-initaws.d  # Init scripts
    restart: unless-stopped

  # AWS CLI Container
  aws-cli:
    image: amazon/aws-cli
    container_name: aws-cli
    networks:
      cloud-net:
        ipv4_address: 172.40.0.11
    environment:
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ENDPOINT_URL=http://localstack:4566
    volumes:
      - ./scripts:/scripts
    entrypoint: ["tail", "-f", "/dev/null"]
    depends_on:
      - localstack
    restart: unless-stopped

  # Pacu - AWS Exploitation Framework
  pacu:
    image: python:3.11-slim
    container_name: pacu
    networks:
      cloud-net:
        ipv4_address: 172.40.0.100
    environment:
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=us-east-1
    volumes:
      - pacu-data:/root/.pacu
    command: >
      bash -c "pip install pacu && tail -f /dev/null"
    depends_on:
      - localstack
    restart: unless-stopped

  # Vulnerable Web App with SSRF
  ssrf-app:
    image: python:3.11-slim
    container_name: ssrf-vulnerable
    ports:
      - "5000:5000"
    networks:
      cloud-net:
        ipv4_address: 172.40.0.20
    volumes:
      - ./challenges/ssrf-app:/app
    working_dir: /app
    environment:
      - AWS_METADATA_URL=http://172.40.0.10:4566
      - FLAG=FLAG{ssrf_to_cloud_metadata_pwned}
    command: >
      bash -c "pip install flask requests && python app.py"
    depends_on:
      - localstack
    restart: unless-stopped

  # Minio (S3-compatible for testing)
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      cloud-net:
        ipv4_address: 172.40.0.21
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - minio-data:/data
    command: server /data --console-address ":9001"
    restart: unless-stopped

volumes:
  localstack-data:
  pacu-data:
  minio-data:
