# Network Penetration Testing Lab
# Usage: docker-compose -f pentest-lab.yaml up -d
# Includes: Vulnerable services, attacker machine, internal network

version: '3.8'

networks:
  external-net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.10.0/24
  internal-net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.20.0/24
    internal: true  # No external access

services:
  # Attacker Machine (Kali/Parrot)
  attacker:
    image: kalilinux/kali-rolling
    container_name: attacker
    stdin_open: true
    tty: true
    networks:
      external-net:
        ipv4_address: 10.10.10.100
    volumes:
      - attacker-data:/root
      - ./tools:/tools
    cap_add:
      - NET_ADMIN
      - NET_RAW
    command: >
      bash -c "apt-get update && apt-get install -y nmap netcat-traditional curl wget && /bin/bash"
    restart: unless-stopped

  # Router/Firewall (simulated)
  router:
    image: alpine
    container_name: router
    networks:
      external-net:
        ipv4_address: 10.10.10.1
      internal-net:
        ipv4_address: 10.10.20.1
    cap_add:
      - NET_ADMIN
    command: >
      sh -c "echo 1 > /proc/sys/net/ipv4/ip_forward &&
             iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE &&
             tail -f /dev/null"
    restart: unless-stopped

  # Web Server (Vulnerable)
  webserver:
    image: vulnerables/web-dvwa
    container_name: webserver
    networks:
      external-net:
        ipv4_address: 10.10.10.10
    ports:
      - "80:80"
    environment:
      - FLAG_1=FLAG{web_server_compromised_a1b2c3}
    restart: unless-stopped

  # FTP Server (Vulnerable)
  ftp:
    image: fauria/vsftpd
    container_name: ftp-server
    networks:
      external-net:
        ipv4_address: 10.10.10.11
    ports:
      - "21:21"
      - "20:20"
      - "21100-21110:21100-21110"
    environment:
      - FTP_USER=admin
      - FTP_PASS=admin123
      - PASV_MIN_PORT=21100
      - PASV_MAX_PORT=21110
    volumes:
      - ftp-data:/home/vsftpd
    restart: unless-stopped

  # SSH Server (Weak credentials)
  ssh-server:
    image: linuxserver/openssh-server
    container_name: ssh-server
    networks:
      external-net:
        ipv4_address: 10.10.10.12
    ports:
      - "2222:2222"
    environment:
      - PUID=1000
      - PGID=1000
      - USER_NAME=admin
      - USER_PASSWORD=password123
      - PASSWORD_ACCESS=true
    volumes:
      - ssh-data:/config
    restart: unless-stopped

  # Internal Database (MySQL)
  database:
    image: mysql:5.7
    container_name: internal-db
    networks:
      internal-net:
        ipv4_address: 10.10.20.10
    environment:
      - MYSQL_ROOT_PASSWORD=SuperSecretPassword123!
      - MYSQL_DATABASE=secrets
      - MYSQL_USER=app
      - MYSQL_PASSWORD=app123
      - FLAG_2=FLAG{database_credentials_leaked_x1y2z3}
    volumes:
      - db-data:/var/lib/mysql
    restart: unless-stopped

  # Internal File Server
  fileserver:
    image: dperson/samba
    container_name: internal-fileserver
    networks:
      internal-net:
        ipv4_address: 10.10.20.11
    environment:
      - USER=smbuser;smbpass
      - SHARE=shared;/shared;yes;no;no;smbuser
    volumes:
      - samba-data:/shared
    restart: unless-stopped

  # Metasploitable 2 (if available)
  metasploitable:
    image: tleemcjr/metasploitable2
    container_name: metasploitable
    networks:
      external-net:
        ipv4_address: 10.10.10.20
    tty: true
    stdin_open: true
    restart: unless-stopped

volumes:
  attacker-data:
  ftp-data:
  ssh-data:
  db-data:
  samba-data:
